{% set name = "pygmailsorter" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygmailsorter-{{ version }}.tar.gz
  sha256: a9393a0d625fa71c8d79712b143459d0e55877b0af265c4cf53d1e325284872a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - google-api-python-client >=2.56.0
    - google-auth >=2.10.0
    - google-auth-oauthlib >=0.5.2
    - numpy >=1.23.1
    - pandas >=1.4.3
    - python >=3.7
    - scikit-learn >=1.1.2
    - sqlalchemy >=1.4.40
    - tqdm >=4.64.0

test:
  imports:
    - pygmailsorter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pygmailsorter
  summary: Assign labels to emails in Google Mail based on their similarity to other emails assigned to the same label.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
