{% set name = "pygmailsorter" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygmailsorter-{{ version }}.tar.gz
  sha256: 7887ee1ab5d351a1275589d9e3bcc7f01f7ddc75d34694a9682c56f2e872d813

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - pygmailsorter = pygmailsorter.__main__:command_line_parser
    - pygmailsorter-daemon = pygmailsorter.__main__:command_line_parser

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - google-api-python-client >=2.92.0
    - google-auth >=2.21.0
    - google-auth-oauthlib >=1.0.0
    - numpy >=1.25.0
    - pandas >=2.0.3
    - python >=3.7
    - scikit-learn >=1.3.0
    - sqlalchemy >=2.0.18
    - tqdm >=4.65.0

test:
  imports:
    - pygmailsorter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pygmailsorter
  summary: Assign labels to emails in Google Mail based on their similarity to other emails assigned to the same label.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
