{% set name = "pygmailsorter" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygmailsorter-{{ version }}.tar.gz
  sha256: 0f2ad8837b5a2f775b9af6f67223c4d61baad63d579e0fed64d46752445006ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - google-api-python-client >=2.65.0
    - google-auth >=2.13.0
    - google-auth-oauthlib >=0.7.0
    - numpy >=1.23.4
    - pandas >=1.5.1
    - python >=3.7
    - scikit-learn >=1.1.3
    - sqlalchemy >=1.4.42
    - tqdm >=4.64.1

test:
  imports:
    - pygmailsorter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pygmailsorter
  summary: Assign labels to emails in Google Mail based on their similarity to other emails assigned to the same label.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
