{% set name = "pygmailsorter" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygmailsorter-{{ version }}.tar.gz
  sha256: dec59f48ae02bfee984c8c9918d921bd8a0a002ce9b03f905ff438ec2a3af5da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - pygmailsorter = pygmailsorter.__main__:command_line_parser
    - pygmailsorter-app = pygmailsorter.webapp.app:run_app
    - pygmailsorter-daemon = pygmailsorter.daemon.__main__:command_line_parser

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - google-api-python-client >=2.92.0
    - google-auth >=2.21.0
    - google-auth-oauthlib >=1.0.0
    - numpy >=1.25.1
    - pandas >=2.0.3
    - python >=3.7
    - scikit-learn >=1.3.0
    - sqlalchemy >=2.0.18
    - tqdm >=4.65.0
    - gunicorn >=20.1.0
    - flask >=2.3.2
    - flask-login >=0.6.2

test:
  imports:
    - pygmailsorter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pygmailsorter
  summary: Assign labels to emails in Google Mail based on their similarity to other emails assigned to the same label.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
